CREATE USER production WITH ENCRYPTED PASSWORD '321321';
CREATE DATABASE fbk_prod_db;
GRANT ALL PRIVILEGES ON DATABASE fbk_prod_db TO production;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO production;
GRANT USAGE ON SCHEMA public TO production;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO production;
ALTER USER production CREATEDB;
ALTER DATABASE fbk_prod_db OWNER TO production;
