# Generated by Django 3.0.8 on 2020-07-26 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='content',
        ),
        migrations.AddField(
            model_name='request',
            name='body',
            field=models.TextField(default='', max_length=5000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='headers',
            field=models.TextField(default='', max_length=5000),
            preserve_default=False,
        ),
    ]
